### ISSUE TITLE
generate ID to replace personally identifiable info

### ISSUE THREAD

**Issue by mscarey** [open-austin/harris-county-bookings#13]
I think instead of simply stripping the personally identifiable info out of the dataset, the scraper should replace it with a persistent ID number for each individual. That would be necessary for any user who was doing a study involving recidivism, and needed to know whether the same person was being arrested on multiple dates.

**Comment by laconc** [comment]
My recommendation is a hashing algorithm. Since such a function always produces the same output hash for the same input message, hashing the person's name and birthday should produce an identifier that's unique and persistent for the individual. This is public data anyway so I don't think we need to go crazy with security here; good old SHA-1 should do it.

**Comment by mscarey** [comment]
@laconc did resolve this by adding a hash of the (non-normalized) name string and the birthdate field. The birthdate field will be standardized; see issue #18.
